### ISSUE TITLE
Full screen mode for videos (Vimeo)

### ISSUE THREAD

**Issue by AvenueSpaces** [luciuschoi/lightbox-bootstrap-rails#5]
Hi,

The full screen mode is not there. I found on another post that there is an error in js files. Instead of me forking the app and editing files, could you please fix the master branch?

Details:
Just look for this string allowfullscreenclass in js and min.js files. The space is missing. The final fix should look like: ...allowfullscreen class...

Much appreciated,
John

**Comment by luciuschoi** [comment]
Thank you.
After fixing the typo you mentioned about, I updated github repository and also rubygem.org.
If you bundle update this gem, new version will be bundled.

**Comment by AvenueSpaces** [comment]
Thank you for your quick action!
